#! /bin/sh
# /etc/init.d/controlcenter
### BEGIN INIT INFO
# Provides:          noip2
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# Some things that run always
touch /var/lock/controlcenter

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script controlcenter "
    java -jar /home/moba/controlcenter-jetty-console.war >> /home/moba/controlcenter.out
    ;;
  stop)
    echo "Stopping script controlcenter"
    echo "Could do more here"
    ;;
  *)
    echo "Usage: /etc/init.d/controlcenter {start|stop}"
    exit 1
    ;;
esac

exit 0

