-- Test data for Integration Tests (H2)
-- Insert test constructions
INSERT INTO construction (id, name)
VALUES (next value for CONSTRUCTION_SEQ, 'Integration Test Construction 1');
INSERT INTO construction (id, name)
VALUES (next value for CONSTRUCTION_SEQ, 'Integration Test Construction 2');

INSERT INTO construction (id, name)
VALUES (40001, 'IT Scenario Execution left and right');

-- Insert test device
INSERT INTO device_info (id, device_key, type)
VALUES (next value for DEVICE_INFO_SEQ, 'TEST', 1);


INSERT INTO TRAIN (ID, ADDRESS, NAME)
VALUES (10001, 5, 'IT train 1');
INSERT INTO TRAIN (ID, ADDRESS, NAME)
VALUES (10002, 6, 'IT train 2');

-- track block

INSERT INTO BUSDATA_CONFIG (ID, CONFIG_ADDRESS, CONFIG_BIT, CONFIG_BIT_STATE, CONFIG_BUS)
VALUES (19201, 50, 1, false, 1);
INSERT INTO BUSDATA_CONFIG (ID, CONFIG_ADDRESS, CONFIG_BIT, CONFIG_BIT_STATE, CONFIG_BUS)
VALUES (19202, 60, 2, false, 1);
INSERT INTO BUSDATA_CONFIG (ID, CONFIG_ADDRESS, CONFIG_BIT, CONFIG_BIT_STATE, CONFIG_BUS)
VALUES (19203, 60, 1, false, 1);
INSERT INTO BUSDATA_CONFIG (ID, CONFIG_ADDRESS, CONFIG_BIT, CONFIG_BIT_STATE, CONFIG_BUS)
VALUES (19204, 70, 2, false, 1);
INSERT INTO BUSDATA_CONFIG (ID, CONFIG_ADDRESS, CONFIG_BIT, CONFIG_BIT_STATE, CONFIG_BUS)
VALUES (20801, 10, 1, false, 1);
INSERT INTO BUSDATA_CONFIG (ID, CONFIG_ADDRESS, CONFIG_BIT, CONFIG_BIT_STATE, CONFIG_BUS)
VALUES (20802, 10, 3, false, 1);


INSERT INTO TRACK_BLOCK (ID, BACKWARDTARGETDRIVINGLEVEL, DRIVINGLEVELADJUSTTYPE, FEEDBACK, FORWARDTARGETDRIVINGLEVEL,
                         NAME, BLOCKFUNCTION_ID, CONSTRUCTION_ID)
VALUES (1601, null, 0, true, null, 'links', 19201, 40001);
INSERT INTO TRACK_BLOCK (ID, BACKWARDTARGETDRIVINGLEVEL, DRIVINGLEVELADJUSTTYPE, FEEDBACK, FORWARDTARGETDRIVINGLEVEL,
                         NAME, BLOCKFUNCTION_ID, CONSTRUCTION_ID)
VALUES (1602, null, 0, true, null, 'mitte nord', 19202, 40001);
INSERT INTO TRACK_BLOCK (ID, BACKWARDTARGETDRIVINGLEVEL, DRIVINGLEVELADJUSTTYPE, FEEDBACK, FORWARDTARGETDRIVINGLEVEL,
                         NAME, BLOCKFUNCTION_ID, CONSTRUCTION_ID)
VALUES (1603, null, 0, true, null, 'mitte süd', 19203, 40001);
INSERT INTO TRACK_BLOCK (ID, BACKWARDTARGETDRIVINGLEVEL, DRIVINGLEVELADJUSTTYPE, FEEDBACK, FORWARDTARGETDRIVINGLEVEL,
                         NAME, BLOCKFUNCTION_ID, CONSTRUCTION_ID)
VALUES (1604, null, 0, true, null, 'rechts', 19204, 40001);

-- TRACK

INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35201, 7, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35202, 10, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35203, 11, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35204, 12, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35207, 12, 3, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35209, 13, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (38404, 13, 3, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35208, 14, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35210, 14, 3, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (38403, 16, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (36801, 16, 3, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35216, 17, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (38402, 17, 3, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (35217, 18, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (1326, 19, 2, 40001);
INSERT INTO GRID_POSITION (ID, X, Y, CONSTRUCTION_ID)
VALUES (19204, 20, 2, 40001);

INSERT INTO TRACKPART_BLOCK_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, BLOCKLENGTH, LEFTTRACKBLOCK_ID, MIDDLETRACKBLOCK_ID, RIGHTTRACKBLOCK_ID) VALUES (20801, 40001, 35201, 0, 3, null, 1601, null);
INSERT INTO TRACKPART_BLOCK_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, BLOCKLENGTH, LEFTTRACKBLOCK_ID, MIDDLETRACKBLOCK_ID, RIGHTTRACKBLOCK_ID) VALUES (20805, 40001, 35208, 0, 2, null, 1602, null);
INSERT INTO TRACKPART_BLOCK_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, BLOCKLENGTH, LEFTTRACKBLOCK_ID, MIDDLETRACKBLOCK_ID, RIGHTTRACKBLOCK_ID) VALUES (20806, 40001, 35210, 0, 2, null, 1603, null);
INSERT INTO TRACKPART_BLOCK_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, BLOCKLENGTH, LEFTTRACKBLOCK_ID, MIDDLETRACKBLOCK_ID, RIGHTTRACKBLOCK_ID) VALUES (20816, 40001, 19204, 0, 2, null, 1604, null);

INSERT INTO TRACKPART_CURVE (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION) VALUES (20807, 40001, 35207, 3);
INSERT INTO TRACKPART_CURVE (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION) VALUES (20813, 40001, 38402, 2);

INSERT INTO TRACKPART_SIGNAL (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, TYPE, SIGNALCONFIGGREEN1_ID,
                              SIGNALCONFIGGREEN2_ID, SIGNALCONFIGRED1_ID, SIGNALCONFIGRED2_ID, SIGNALCONFIGWHITE_ID,
                              SIGNALCONFIGYELLOW1_ID, SIGNALCONFIGYELLOW2_ID, STOPBLOCK_ID)
VALUES (20802, 40001, 35202, 0, 0, null, null, null, null, null, null, null, null);
INSERT INTO TRACKPART_SIGNAL (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, TYPE, SIGNALCONFIGGREEN1_ID,
                              SIGNALCONFIGGREEN2_ID, SIGNALCONFIGRED1_ID, SIGNALCONFIGRED2_ID, SIGNALCONFIGWHITE_ID,
                              SIGNALCONFIGYELLOW1_ID, SIGNALCONFIGYELLOW2_ID, STOPBLOCK_ID)
VALUES (20808, 40001, 35209, 0, 0, null, null, null, null, null, null, null, null);
INSERT INTO TRACKPART_SIGNAL (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, TYPE, SIGNALCONFIGGREEN1_ID,
                              SIGNALCONFIGGREEN2_ID, SIGNALCONFIGRED1_ID, SIGNALCONFIGRED2_ID, SIGNALCONFIGWHITE_ID,
                              SIGNALCONFIGYELLOW1_ID, SIGNALCONFIGYELLOW2_ID, STOPBLOCK_ID)
VALUES (20809, 40001, 36801, 0, 0, null, null, null, null, null, null, null, null);
INSERT INTO TRACKPART_SIGNAL (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION, TYPE, SIGNALCONFIGGREEN1_ID,
                              SIGNALCONFIGGREEN2_ID, SIGNALCONFIGRED1_ID, SIGNALCONFIGRED2_ID, SIGNALCONFIGWHITE_ID,
                              SIGNALCONFIGYELLOW1_ID, SIGNALCONFIGYELLOW2_ID, STOPBLOCK_ID)
VALUES (20815, 40001, 1326, 0, 0, null, null, null, null, null, null, null, null);

INSERT INTO TRACKPART_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION) VALUES (20803, 40001, 35203, 0);
INSERT INTO TRACKPART_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION) VALUES (20814, 40001, 35217, 0);
INSERT INTO TRACKPART_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION) VALUES (22401, 40001, 38403, 0);
INSERT INTO TRACKPART_STRAIGHT (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, DIRECTION) VALUES (22402, 40001, 38404, 0);

INSERT INTO TRACKPART_SWITCH (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, CURRENTDIRECTION, CURRENTPRESENTATION, EVENTCONFIGURATION_ID, TOGGLEFUNCTION_ID) VALUES (20804, 40001, 35204, 0, 0, null, 20801);
INSERT INTO TRACKPART_SWITCH (ID, CONSTRUCTION_ID, GRIDPOSITION_ID, CURRENTDIRECTION, CURRENTPRESENTATION, EVENTCONFIGURATION_ID, TOGGLEFUNCTION_ID) VALUES (20812, 40001, 35216, 1, 1, null, 20802);


-- scenario

INSERT INTO SCENARIO_ROUTE (ID, NAME, ONEWAY, END_ID, START_ID, CONSTRUCTION_ID)
VALUES (3201, 'left start', false, 1603, 20801, 40001);
INSERT INTO SCENARIO_ROUTE (ID, NAME, ONEWAY, END_ID, START_ID, CONSTRUCTION_ID)
VALUES (3202, 'right ende', false, 1604, 20806, 40001);
INSERT INTO SCENARIO_ROUTE (ID, NAME, ONEWAY, END_ID, START_ID, CONSTRUCTION_ID)
VALUES (3203, 'right start', false, 1602, 20816, 40001);
INSERT INTO SCENARIO_ROUTE (ID, NAME, ONEWAY, END_ID, START_ID, CONSTRUCTION_ID)
VALUES (3204, 'left ende', false, 1601, 20805, 40001);


INSERT INTO SCENARIO (ID, CRON, NAME, STARTDRIVINGLEVEL, STATIONPLATFORMENDID, STATIONPLATFORMSTARTID,
                      TRAINDRIVINGDIRECTION, TRAIN_ID, CONSTRUCTION_ID)
VALUES (9601, '', 'left to right', 10, null, null, 0, 10001, 40001);
INSERT INTO SCENARIO (ID, CRON, NAME, STARTDRIVINGLEVEL, STATIONPLATFORMENDID, STATIONPLATFORMSTARTID,
                      TRAINDRIVINGDIRECTION, TRAIN_ID, CONSTRUCTION_ID)
VALUES (9602, '', 'right to left', 12, null, null, 1, 10002, 40001);

INSERT INTO SCENARIO_SEQUENCE (ID, ENDDELAYINSECONDS, POSITION, ROUTE_ID, SCENARIO_ID) VALUES (3201, 0, 0, 3203, 9602);
INSERT INTO SCENARIO_SEQUENCE (ID, ENDDELAYINSECONDS, POSITION, ROUTE_ID, SCENARIO_ID) VALUES (4801, 0, 1, 3204, 9602);
INSERT INTO SCENARIO_SEQUENCE (ID, ENDDELAYINSECONDS, POSITION, ROUTE_ID, SCENARIO_ID) VALUES (6401, 0, 0, 3201, 9601);
INSERT INTO SCENARIO_SEQUENCE (ID, ENDDELAYINSECONDS, POSITION, ROUTE_ID, SCENARIO_ID) VALUES (6402, 0, 1, 3202, 9601);
