INSERT INTO PUBLIC.CONFIG_VALUE(CONFIG_KEY, CONFIG_VALUE)
VALUES ('HP0_AFTER_TRAIN_PASS_DELAY_IN_SECONDS', '15');
INSERT INTO PUBLIC.CONFIG_VALUE(CONFIG_KEY, CONFIG_VALUE)
VALUES ('START_TRAIN_DELAY_SECONDS', '3');
INSERT INTO PUBLIC.CONFIG_VALUE(CONFIG_KEY, CONFIG_VALUE)
VALUES ('FINISH_ROUTE_DELAY_SECONDS', '3');
INSERT INTO PUBLIC.CONFIG_VALUE(CONFIG_KEY, CONFIG_VALUE)
VALUES ('DEFAULT_START_DRIVING_LEVEL', '10');
INSERT INTO PUBLIC.CONFIG_VALUE(CONFIG_KEY, CONFIG_VALUE)
VALUES ('WAIT_FOR_FREE_TACK_TIMEOUT_IN_MINUTES', '10');